const products = [
    {
        _id:'1',
        name: 'Product_Name',
        image: '/Images/fashion/img-1.webp',
        descripation: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
        brand: 'cipla',
        category: 'Nutriation',
        price: 99,
        countInStock:3,
        rating:3.5,
        numReviews:4,
    },
    {
        _id:'2',
        name: 'Product_Name',
        image: '/images/fashion//img-2.webp',
        descripation: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
        brand: 'cipla',
        category: 'Nutriation',
        price: 99,
        countInStock:3,
        rating:2.5,
        numReviews:4,
    },
    {
        _id:'3',
        name: 'Product_Name',
        image: '/images/fashion//img-3.webp',
        descripation: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
        brand: 'cipla',
        category: 'Nutriation',
        price: 99,
        countInStock:3,
        rating:1.5,
        numReviews:4,
    },
    {
        _id:'4',
        name: 'Product_Name',
        image: '/images/fashion//img-4.webp',
        descripation: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
        brand: 'cipla',
        category: 'Nutriation',
        price: 99,
        countInStock:3,
        rating:3.5,
        numReviews:4,
    },
    {
        _id:'5',
        name: 'Product_Name',
        image: '/images/fashion//img-5.webp',
        descripation: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
        brand: 'cipla',
        category: 'Nutriation',
        price: 99,
        countInStock:3,
        rating:2.5,
        numReviews:4,
    },
   
]

export default products;